#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LCD_NO_SAFETY
#define MENU_NUM 1

#include "BCI_V3\Bulldog_Core_Includes.h"

menu *mainBatteryMenu;

void pre_auton()
{
	addMotor(leftDrive);
	addMotor(rightDrive);
	addMotor(lift);
	addMotor(claw);

	string batteryVoltageString = nAvgBatteryLevel;
	mainBatteryMenu = newMenu(batteryVoltageString);

	startTask(updateLCDTask);
}

task main()
{
	pre_auton();

	//Drivetrain variables
	int leftV, rightV;

	startTask(motorSlewRateTask);

	while (true)
	{
		/* ------------ DRIVETRAIN ------------ */

		//Grab values from joystick
		leftV = vexRT[JOY_JOY_LV];
		rightV = vexRT[JOY_JOY_RV];

		//Bound joystick values
		leftV = abs(leftV) < JOY_THRESHOLD ? 0 : leftV;
		rightV = abs(rightV) < JOY_THRESHOLD ? 0 : rightV;

		//Send powers to motors
		setMotorSpeed(leftDrive, leftV);
		setMotorSpeed(rightDrive, rightV);

		/* --------------- LIFT --------------- */

		if (vexRT[JOY_TRIG_LU])
		{
			setMotorSpeed(lift, 100);
		}
		else if (vexRT[JOY_TRIG_LD])
		{
			setMotorSpeed(lift, -60);
		}
		else
		{
			setMotorSpeed(lift, 0);
		}

		/* --------------- CLAW --------------- */

		if (vexRT[JOY_TRIG_RU])
		{
			setMotorSpeed(claw, 60);
		}
		else if (vexRT[JOY_TRIG_RD])
		{
			setMotorSpeed(claw, -60);
		}
		else
		{
			setMotorSpeed(claw, 0);
		}
	}
}

void invoke(int func)
{
}
