#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelX,         sensorAccelerometer)
#pragma config(Sensor, in3,    accelY,         sensorAccelerometer)
#pragma config(Sensor, in4,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  leftDriveQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightDriveQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftIntakeQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightIntakeQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftShifter,    sensorDigitalOut)
#pragma config(Sensor, dgtl10, rightShifter,   sensorDigitalOut)
#pragma config(Motor,  port1,           leftIntake,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDriveFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftLauncherTop, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLauncherTop, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLauncherBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLauncherBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightIntake,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define MENU_NUM 1
//#define LCD_NO_SAFETY

//#include "autonFunctions.c"
#include "BCI_V3\Bulldog_Core_Includes.h"
#include "BCI_V3\Modules\Core\collisionVector2f.c"

collisionVector2f collVec;
byte dataX[400], dataY[400];
float velX = 0, velY = 0;

task main()
{
	//menu *collisionMenu = newMenu("false");
	//startTask(updateLCDTask);

	//startTask(monitorForCollision, kDefaultTaskPriority + 1);

	//wait1Msec(500);
	//forceTrig = true;
	//changeMessage(collisionMenu, "true");
	//wait1Msec(500);
	//forceTrig = false;
	//changeMessage(collisionMenu, "false");

	//Generate collision data
	for (int i = 0; i < 400; i++)
	{
		dataX[i] = 10;
		dataY[i] = 5;
	}

	//Calculate displacement
	for (int i = 0; i < 400; i++)
	{
		velX += dataX[i] * 0.005;
		velY += dataY[i] * 0.005;
		collVec.x += velX * 0.005;
		collVec.y += velY * 0.005;
	}

	//Convert meters to inches
	collVec.x *= 39.3701;
	collVec.y *= 39.3701;

	writeDebugStreamLine("%2.4f, %2.4f", collVec.x, collVec.y);

	while (true) { wait1Msec(1); }
}

void invoke(int func) {}
