#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    accelX,         sensorAccelerometer)
#pragma config(Sensor, in4,    accelY,         sensorAccelerometer)
#pragma config(Sensor, in5,    leftLineSensor, sensorLineFollower)
#pragma config(Sensor, in6,    rightLineSensor, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightLauncherQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  brake,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  leftLauncherQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftDriveQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  rightDriveQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl10, shifter,        sensorDigitalOut)
#pragma config(Sensor, dgtl11, intakeLimit,    sensorTouch)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftLauncherBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLauncherTop, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightLauncherBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLauncherTop, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftDriveFront, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BCI_V3\Modules\Core\motorControl.c"

void setupMotors()
{
	//Hand motors to slew rate controller
	addMotor(intake);
	addMotor(leftDriveFront, MOTOR_FAST_SLEW_RATE);
	addMotor(rightDriveFront, MOTOR_FAST_SLEW_RATE);
	addMotor(leftLauncherTop, 0.7);
	addMotor(rightLauncherTop, 0.7);
	addMotor(rightLauncherBottom, 0.7);
	addMotor(leftLauncherBottom, 0.7);
	addMotor(rightDriveBack, MOTOR_FAST_SLEW_RATE);
	addMotor(leftDriveBack, MOTOR_FAST_SLEW_RATE);
}

task main()
{
	setupMotors();

	startTask(motorSlewRateTask);

	setMotorSpeed(leftLauncherTop, 127);
	setMotorSpeed(leftLauncherBottom, 127);
	setMotorSpeed(rightLauncherTop, 127);
	setMotorSpeed(rightLauncherBottom, 127);

	while (true) { wait1Msec(1000); }
}
