#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           rightBottomLift, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMiddle,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightTop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightMiddle,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightBottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftTopLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightTopLift,  tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

#define FOUR_MOTOR_TANK_DRIVE
#define DRIVE_USING_QUADRATURE_ENCODERS
//#define DRIVE_USING_INTEGRATED_MOTOR_ENCODERS
#define DRIVE_USING_GYRO
#define DRIVE_USING_TANK_CONTROL

#define FOUR_MOTOR_LIFT
#define LIFT_USING_RIGHT_HANDED_CONTROL

int wheelDiameter = 4;
int eDriveTicks = 627;
float eTurnTicks = 6.56;

#include "Bulldog_Competition_Includes.h"

void pre_auton()
{
	//bStopTasksBetweenModes = true;

	setDrive(addMotor(leftTop), addMotor(leftBottom), addMotor(rightTop), addMotor(rightBottom), leftQuad, rightQuad, gyro, 15);
	setLift(addMotor(leftTopLift), addMotor(leftBottomLift), addMotor(rightTopLift), addMotor(rightBottomLift), 100, -20, 10);
}

task autonomous()
{

}

task usercontrol()
{
	startTask(motorSlewRateTask);
	startTask(driveJoystickControl);
	startTask(liftJoystickControl);

	driveTime(1, 1, 1);
	driveQuad(1, 1);
	//driveIME(1, 1);

	turnTime(1, 1);
	turnQuad(1, 1);
	//turnIME(1, 1);
	turnGyro(1, 1);
}

void invoke(int func)
{
	switch (func)
	{
		case 0:
			break;

		default:
			break;
	}
}
